//! In-app deployment sessions (spec §6.7). The embedded Worker bundle, and the one deployment in
//! progress, which holds the API token and the setup token in Rust memory only. The WebView names
//! the deployment by an opaque handle.

use std::sync::{Arc, Mutex, OnceLock};

use hatoba_core::sync::deploy::{Deployment, WorkerBundle};

use crate::error::{AppError, AppResult, ErrorCode};

/// Generated by `scripts/worker/bundle.mjs` and copied by `build.rs`; empty when the build has none.
const BUNDLE_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/worker-bundle.json"));

/// The embedded Worker bundle (DEPLOY-01).
pub fn bundle() -> AppResult<Arc<WorkerBundle>> {
    static BUNDLE: OnceLock<Result<Arc<WorkerBundle>, String>> = OnceLock::new();
    if BUNDLE_JSON.trim().is_empty() {
        return Err(AppError::new(
            ErrorCode::NoWorkerBundle,
            "this build has no Worker bundle",
        ));
    }
    BUNDLE
        .get_or_init(|| {
            WorkerBundle::parse(BUNDLE_JSON)
                .map(Arc::new)
                .map_err(|e| e.to_string())
        })
        .clone()
        .map_err(AppError::internal)
}

struct Current {
    handle: String,
    deployment: Arc<tokio::sync::Mutex<Deployment>>,
}

/// The deployment in progress, if any. Dropping it wipes its tokens.
#[derive(Default)]
pub struct Deployments {
    current: Mutex<Option<Current>>,
}

impl Deployments {
    fn current(&self) -> std::sync::MutexGuard<'_, Option<Current>> {
        self.current.lock().unwrap_or_else(|p| p.into_inner())
    }

    /// Makes `deployment` the current one, ending any other, and returns its handle.
    pub fn start(&self, deployment: Deployment) -> String {
        let handle = uuid::Uuid::now_v7().to_string();
        *self.current() = Some(Current {
            handle: handle.clone(),
            deployment: Arc::new(tokio::sync::Mutex::new(deployment)),
        });
        handle
    }

    pub fn get(&self, handle: &str) -> AppResult<Arc<tokio::sync::Mutex<Deployment>>> {
        self.current()
            .as_ref()
            .filter(|c| c.handle == handle)
            .map(|c| Arc::clone(&c.deployment))
            .ok_or_else(|| AppError::new(ErrorCode::Cancelled, "the deployment has ended"))
    }

    /// Ends the deployment named by `handle`. A command still running on it keeps it until it
    /// returns.
    pub fn end(&self, handle: &str) {
        let mut current = self.current();
        if current.as_ref().is_some_and(|c| c.handle == handle) {
            *current = None;
        }
    }

    /// Ends any deployment (when the vault locks).
    pub fn clear(&self) {
        *self.current() = None;
    }
}
