// Generated by tauri-specta from src-tauri. Do not edit.
// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Opens the Windows 11 Snap Layouts flyout (hovering the custom maximize button, WIN-01). */
	windowSnapOverlay: () => __TAURI_INVOKE<void>("window_snap_overlay"),
	/**  Writes text to a path the user chose in the native save dialog (recovery code "Save as Text"). */
	saveTextFile: (path: string, contents: string) => __TAURI_INVOKE<null>("save_text_file", { path, contents }),
	/**  Feeds the idle auto-lock timer (SEC-02). */
	activityPing: () => __TAURI_INVOKE<void>("activity_ping"),
	/**
	 *  Asks GitHub whether a newer version exists (Settings → About). Runs only when the user
	 *  checks, or after unlock when they turned on the automatic check.
	 */
	updateCheck: () => __TAURI_INVOKE<UpdateCheck>("update_check"),
	/**
	 *  Downloads and installs the update the last check found. Hatoba closes, which ends every SSH
	 *  session, and the installer starts the new version.
	 */
	updateInstall: (progress: Channel<UpdateProgress>) => __TAURI_INVOKE<null>("update_install", { progress }),
	vaultStatus: () => __TAURI_INVOKE<VaultStatus>("vault_status"),
	/**  VAULT-01/02: creates the vault and returns the recovery code (shown exactly once). */
	vaultCreate: (password: string) => __TAURI_INVOKE<string>("vault_create", { password }),
	/**  VAULT-03 / SEC-06: wrong passwords are throttled with increasing delays (persisted). */
	vaultUnlock: (password: string) => __TAURI_INVOKE<null>("vault_unlock", { password }),
	/**  SEC-07 (P1): Windows Hello. */
	vaultUnlockBiometric: () => __TAURI_INVOKE<null>("vault_unlock_biometric"),
	vaultLock: () => __TAURI_INVOKE<void>("vault_lock"),
	vaultVerifyPassword: (password: string) => __TAURI_INVOKE<boolean>("vault_verify_password", { password }),
	/**
	 *  VAULT-05: re-wraps only the vault key (no item is re-encrypted); with sync, the server copy is
	 *  updated atomically and other devices' sessions are revoked.
	 */
	vaultChangePassword: (current: string, next: string) => __TAURI_INVOKE<null>("vault_change_password", { current, next }),
	/**  VAULT-06: resets the master password with the recovery code. Works offline when sync is off. */
	vaultRecover: (recoveryCode: string, newPassword: string) => __TAURI_INVOKE<null>("vault_recover", { recoveryCode, newPassword }),
	/**  Flow B (§6.6): first launch on a new device — download the vault from the cloud. */
	vaultRestoreFromCloud: (config: SyncConfigInput, password: string) => __TAURI_INVOKE<null>("vault_restore_from_cloud", { config, password }),
	/**  VAULT-07: single-file encrypted backup in the same envelope format. */
	vaultExportBackup: (path: string) => __TAURI_INVOKE<null>("vault_export_backup", { path }),
	/**  Issues a new recovery code (the old one stops working everywhere once synced). */
	vaultRotateRecovery: (password: string) => __TAURI_INVOKE<string>("vault_rotate_recovery", { password }),
	/**  SEC-07 (P1): enrol Windows Hello. Requires the master password as a fresh confirmation. */
	biometricEnable: (password: string) => __TAURI_INVOKE<null>("biometric_enable", { password }),
	biometricDisable: () => __TAURI_INVOKE<null>("biometric_disable"),
	hostsList: () => __TAURI_INVOKE<HostView[]>("hosts_list"),
	hostGet: (id: string) => __TAURI_INVOKE<HostView>("host_get", { id }),
	hostSave: (input: HostInput) => __TAURI_INVOKE<HostView>("host_save", { input }),
	hostDelete: (id: string) => __TAURI_INVOKE<null>("host_delete", { id }),
	hostDuplicate: (id: string) => __TAURI_INVOKE<HostView>("host_duplicate", { id }),
	hostSetFavorite: (id: string, favorite: boolean) => __TAURI_INVOKE<null>("host_set_favorite", { id, favorite }),
	/**  Turns the resource usage in a host's terminals on or off on this device (TERM-12). */
	hostSetShowStats: (id: string, on: boolean) => __TAURI_INVOKE<null>("host_set_show_stats", { id, on }),
	/**
	 *  SEC-08: copies a saved host password to the clipboard from Rust (it never reaches the WebView)
	 *  and clears it after 30 s if the clipboard still holds it.
	 */
	hostCopyPassword: (id: string) => __TAURI_INVOKE<null>("host_copy_password", { id }),
	groupsList: () => __TAURI_INVOKE<GroupView[]>("groups_list"),
	groupSave: (input: GroupInput) => __TAURI_INVOKE<GroupView>("group_save", { input }),
	groupDelete: (id: string) => __TAURI_INVOKE<null>("group_delete", { id }),
	tagsList: () => __TAURI_INVOKE<TagCount[]>("tags_list"),
	/**  HOST-10: TCP connect only (no authentication), 3 s timeout, probed concurrently. */
	hostsProbe: (ids: string[]) => __TAURI_INVOKE<ProbeResult[]>("hosts_probe", { ids }),
	sshConfigPreview: () => __TAURI_INVOKE<SshConfigCandidate[]>("ssh_config_preview"),
	/**  SSH-11: creates hosts (and imports unencrypted identity files as keys) for the chosen aliases. */
	sshConfigImport: (aliases: string[]) => __TAURI_INVOKE<ImportResult>("ssh_config_import", { aliases }),
	keysList: () => __TAURI_INVOKE<KeyView[]>("keys_list"),
	/**  KEY-01 / WIN-09: OpenSSH, PEM and PuTTY .ppk, from a file or pasted text, with clear errors. */
	keyImport: (input: KeyImportInput) => __TAURI_INVOKE<KeyView>("key_import", { input }),
	/**  KEY-02: Ed25519 by default, RSA 4096 optional. */
	keyGenerate: (input: KeyGenerateInput) => __TAURI_INVOKE<KeyView>("key_generate", { input }),
	keyRename: (id: string, name: string) => __TAURI_INVOKE<KeyView>("key_rename", { id, name }),
	/**  KEY-05: the UI lists the hosts using the key before calling this; they fall back to "ask". */
	keyDelete: (id: string) => __TAURI_INVOKE<null>("key_delete", { id }),
	keyPublic: (id: string) => __TAURI_INVOKE<string>("key_public", { id }),
	/**
	 *  KEY-06: appends the public key to `~/.ssh/authorized_keys` on a host (like `ssh-copy-id`).
	 *  The key travels on stdin, so nothing from it is interpreted by the remote shell.
	 */
	keyDeploy: (keyId: string, hostId: string) => __TAURI_INVOKE<null>("key_deploy", { keyId, hostId }),
	sshConnect: (hostId: string, options: ConnectOptions, channel: Channel<TermFrame>) => __TAURI_INVOKE<string>("ssh_connect", { hostId, options, channel }),
	/**
	 *  Quick connect (HOST-12): a terminal on a target typed into the hosts search field, which is
	 *  not saved as a host. Authentication is the ssh-agent, then the server's keyboard-interactive
	 *  prompts or a password asked once (SSH-03, SSH-08, SSH-09); the host key goes through the
	 *  usual check and is saved like any other (SSH-04).
	 */
	sshConnectTarget: (target: QuickTarget, options: ConnectOptions, channel: Channel<TermFrame>) => __TAURI_INVOKE<string>("ssh_connect_target", { target, options, channel }),
	/**  The recent quick-connect targets on this device, newest first. */
	recentTargetsList: () => __TAURI_INVOKE<QuickTarget[]>("recent_targets_list"),
	/**  Forgets one recent target and returns what is left. */
	recentTargetRemove: (target: QuickTarget) => __TAURI_INVOKE<QuickTarget[]>("recent_target_remove", { target }),
	sshWrite: (sessionId: string, data: string) => __TAURI_INVOKE<null>("ssh_write", { sessionId, data }),
	sshResize: (sessionId: string, cols: number, rows: number) => __TAURI_INVOKE<null>("ssh_resize", { sessionId, cols, rows }),
	sshDisconnect: (sessionId: string) => __TAURI_INVOKE<null>("ssh_disconnect", { sessionId }),
	/**
	 *  Starts reading the server's resource usage for the terminal's status bar (TERM-12), in
	 *  place of a sampling already running on the session. Readings stream on `channel` until
	 *  `ssh_stats_stop` with the returned id, the end of the session, or the WebView dropping the
	 *  channel. When starts overlap, the one that arrived last keeps running.
	 */
	sshStatsStart: (sessionId: string, channel: Channel<StatsEvent>) => __TAURI_INVOKE<number>("ssh_stats_start", { sessionId, channel }),
	/**  Stops the sampling that `ssh_stats_start` returned `stats_id` for; a later one keeps running. */
	sshStatsStop: (sessionId: string, statsId: number) => __TAURI_INVOKE<void>("ssh_stats_stop", { sessionId, statsId }),
	/**  "Test connection" in the host editor: connect, authenticate, verify the host key, disconnect. */
	sshTest: (input: HostInput) => __TAURI_INVOKE<TestResult>("ssh_test", { input }),
	hostkeyRespond: (requestId: string, accept: boolean) => __TAURI_INVOKE<void>("hostkey_respond", { requestId, accept }),
	authPromptRespond: (requestId: string, answers: string[] | null) => __TAURI_INVOKE<void>("auth_prompt_respond", { requestId, answers }),
	forwardsList: (hostId: string) => __TAURI_INVOKE<ForwardView[]>("forwards_list", { hostId }),
	forwardSave: (input: ForwardInput) => __TAURI_INVOKE<ForwardView>("forward_save", { input }),
	forwardDelete: (id: string) => __TAURI_INVOKE<null>("forward_delete", { id }),
	forwardStart: (sessionId: string, forwardId: string) => __TAURI_INVOKE<number>("forward_start", { sessionId, forwardId }),
	forwardStop: (sessionId: string, forwardId: string) => __TAURI_INVOKE<null>("forward_stop", { sessionId, forwardId }),
	/**  Forwards currently running on a session: `(forward_id, local_port)`. */
	forwardsActive: (sessionId: string) => __TAURI_INVOKE<([string, number])[]>("forwards_active", { sessionId }),
	sftpHome: (sessionId: string) => __TAURI_INVOKE<string>("sftp_home", { sessionId }),
	sftpList: (sessionId: string, path: string) => __TAURI_INVOKE<FileEntry[]>("sftp_list", { sessionId, path }),
	/**  SFTP-02 download. `local_path` comes from the native save dialog. */
	sftpDownload: (sessionId: string, remotePath: string, localPath: string) => __TAURI_INVOKE<string>("sftp_download", { sessionId, remotePath, localPath }),
	/**  SFTP-02 upload into `remote_dir` (file picker or drag & drop). */
	sftpUpload: (sessionId: string, localPath: string, remoteDir: string) => __TAURI_INVOKE<string>("sftp_upload", { sessionId, localPath, remoteDir }),
	sftpRename: (sessionId: string, from: string, to: string) => __TAURI_INVOKE<null>("sftp_rename", { sessionId, from, to }),
	sftpRemove: (sessionId: string, path: string, isDir: boolean) => __TAURI_INVOKE<null>("sftp_remove", { sessionId, path, isDir }),
	sftpMkdir: (sessionId: string, path: string) => __TAURI_INVOKE<null>("sftp_mkdir", { sessionId, path }),
	transferCancel: (transferId: string) => __TAURI_INVOKE<void>("transfer_cancel", { transferId }),
	syncStatus: () => __TAURI_INVOKE<SyncStatus>("sync_status"),
	/**  Wizard "Test connection": Worker `/v1/health`, or (D1 mode) token check + database list. */
	syncTest: (config: SyncConfigInput) => __TAURI_INVOKE<SyncTestResult>("sync_test", { config }),
	/**  Flow A (§6.6): initialise the remote with this vault, sign in and push everything. */
	syncConfigure: (config: SyncConfigInput, password: string) => __TAURI_INVOKE<null>("sync_configure", { config, password }),
	syncNow: () => __TAURI_INVOKE<null>("sync_now"),
	/**  Re-authenticate after "认证失效" (session expired or revoked). */
	syncLogin: (password: string) => __TAURI_INVOKE<null>("sync_login", { password }),
	/**  The sync status page opened: reads the Worker's `/v1/health` (§6.7, Upgrades). */
	syncCheckWorker: () => __TAURI_INVOKE<void>("sync_check_worker"),
	/**  Hides "Worker update available" until the app bundles a newer Worker version. */
	syncDismissWorkerUpdate: () => __TAURI_INVOKE<null>("sync_dismiss_worker_update"),
	syncSetAuto: (enabled: boolean) => __TAURI_INVOKE<void>("sync_set_auto", { enabled }),
	/**  Stops syncing on this device. Local data and the remote copy are both kept. */
	syncDisconnect: () => __TAURI_INVOKE<null>("sync_disconnect"),
	syncDevices: () => __TAURI_INVOKE<DeviceView[]>("sync_devices"),
	syncRevokeDevice: (deviceId: string) => __TAURI_INVOKE<null>("sync_revoke_device", { deviceId }),
	/**  §6.4: conflicts are resolved automatically; this lists the unreviewed ones (P1). */
	syncConflicts: () => __TAURI_INVOKE<ConflictView[]>("sync_conflicts"),
	syncConflictResolve: (id: number, action: ConflictAction) => __TAURI_INVOKE<null>("sync_conflict_resolve", { id, action }),
	/**
	 *  Step 1 (DEPLOY-02): checks the API token. The token crosses to Rust here once; every later
	 *  call names the deployment by the returned handle (DEPLOY-07).
	 */
	deployStart: (apiToken: string, accountId: string | null) => __TAURI_INVOKE<DeployStart>("deploy_start", { apiToken, accountId }),
	/**  Step 2: what the deployment will do, before anything is written. */
	deployInspect: (handle: string, target: DeployTarget) => __TAURI_INVOKE<DeployPlan>("deploy_inspect", { handle, target }),
	/**
	 *  Steps 2 to 8 (DEPLOY-03), reporting each step on `progress`. Run it again after a failure to
	 *  continue the deployment (DEPLOY-05).
	 */
	deployRun: (handle: string, target: DeployTarget, progress: Channel<DeployProgress>) => __TAURI_INVOKE<DeployOutcome>("deploy_run", { handle, target, progress }),
	/**  "Check again" while step 8 waits for the Worker. */
	deployCheck: (handle: string) => __TAURI_INVOKE<boolean>("deploy_check", { handle }),
	/**  "Remove what Hatoba created": only what this deployment created (DEPLOY-05). */
	deployCleanup: (handle: string) => __TAURI_INVOKE<null>("deploy_cleanup", { handle }),
	/**  Ends the deployment and forgets its tokens (the user cancelled or left the wizard). */
	deployCancel: (handle: string) => __TAURI_INVOKE<void>("deploy_cancel", { handle }),
	/**
	 *  The master password step after a deployment: Flow A step 3 (§6.6) with the Worker URL and the
	 *  setup token from the deployment, then deletes the `SETUP_TOKEN` secret (DEPLOY-06) and ends
	 *  the deployment.
	 */
	deploySetup: (handle: string, password: string) => __TAURI_INVOKE<null>("deploy_setup", { handle, password }),
	/**
	 *  What "Update Worker" starts from (DEPLOY-08): the account ID and Worker name recorded when the
	 *  app deployed the Worker, or else the name in its workers.dev URL.
	 */
	deployUpgradeDefaults: () => __TAURI_INVOKE<UpgradeDefaults>("deploy_upgrade_defaults"),
	/**  Step 2 of an upgrade: what it will do, before anything is written. */
	deployUpgradeInspect: (handle: string, target: UpgradeTarget) => __TAURI_INVOKE<UpgradePlan>("deploy_upgrade_inspect", { handle, target }),
	/**
	 *  "Update Worker" (DEPLOY-08): the deployment steps as an upgrade, reporting each step on
	 *  `progress`. Run it again after a failure to continue the upgrade.
	 */
	deployUpgrade: (handle: string, target: UpgradeTarget, progress: Channel<DeployProgress>) => __TAURI_INVOKE<DeployOutcome>("deploy_upgrade", { handle, target, progress }),
	settingsGet: () => __TAURI_INVOKE<SettingsView>("settings_get"),
	settingsSave: (settings: SettingsView) => __TAURI_INVOKE<null>("settings_save", { settings }),
	/**  Readable while locked: the unlock screen needs the language. */
	prefsGet: () => __TAURI_INVOKE<LocalPrefs>("prefs_get"),
	prefsSave: (prefs: LocalPrefs) => __TAURI_INVOKE<null>("prefs_save", { prefs }),
	/**  The sidebar's star prompt (spec §9). The first read records when this device started waiting. */
	starPromptGet: () => __TAURI_INVOKE<StarPrompt>("star_prompt_get"),
	/**  The user starred, opened the bug report form, or closed the prompt: it never shows again. */
	starPromptDone: () => __TAURI_INVOKE<null>("star_prompt_done"),
	aiProvidersList: () => __TAURI_INVOKE<AiProviderView[]>("ai_providers_list"),
	aiProviderSave: (input: AiProviderInput) => __TAURI_INVOKE<AiProviderView>("ai_provider_save", { input }),
	aiProviderDelete: (id: string) => __TAURI_INVOKE<null>("ai_provider_delete", { id }),
	/**  AI-03: the model list of a saved or unsaved provider. */
	aiProviderModels: (input: AiProviderInput) => __TAURI_INVOKE<AiModel[]>("ai_provider_models", { input }),
	/**  AI-04: a minimal request to the first model, or the model list when there is none. */
	aiProviderTest: (input: AiProviderInput) => __TAURI_INVOKE<AiTestResult>("ai_provider_test", { input }),
	searchProvidersList: () => __TAURI_INVOKE<SearchProviderView[]>("search_providers_list"),
	searchProviderSave: (input: SearchProviderInput) => __TAURI_INVOKE<SearchProviderView>("search_provider_save", { input }),
	searchProviderDelete: (id: string) => __TAURI_INVOKE<null>("search_provider_delete", { id }),
	/**  A real query through a saved or unsaved search provider. */
	searchProviderTest: (input: SearchProviderInput) => __TAURI_INVOKE<AiTestResult>("search_provider_test", { input }),
	aiSettingsGet: () => __TAURI_INVOKE<AiSettingsView>("ai_settings_get"),
	aiSettingsSave: (settings: AiSettingsView) => __TAURI_INVOKE<null>("ai_settings_save", { settings }),
	/**  Every conversation, unsorted; the panel sorts by `last_activity`, pinned first. */
	aiConversationsList: () => __TAURI_INVOKE<AiConversationView[]>("ai_conversations_list"),
	aiConversationGet: (id: string) => __TAURI_INVOKE<AiConversationDetail>("ai_conversation_get", { id }),
	aiConversationRename: (id: string, title: string) => __TAURI_INVOKE<AiConversationView>("ai_conversation_rename", { id, title }),
	aiConversationPin: (id: string, pinned: boolean) => __TAURI_INVOKE<AiConversationView>("ai_conversation_pin", { id, pinned }),
	aiConversationDelete: (id: string) => __TAURI_INVOKE<null>("ai_conversation_delete", { id }),
	/**
	 *  Stores the user's message and starts a turn; its events stream on `channel` until
	 *  `turn_ended`.
	 */
	aiSend: (input: AiSendInput, channel: Channel<AiTurnEvent>) => __TAURI_INVOKE<AiSendStarted>("ai_send", { input, channel }),
	/**  Retry after an error: the next request from the stored conversation, on a new channel. */
	aiRetry: (conversationId: string, context: AiTurnContext, channel: Channel<AiTurnEvent>) => __TAURI_INVOKE<null>("ai_retry", { conversationId, context, channel }),
	/**  Stores a result the frontend produced (`read_terminal`, `send_input`, a rejection). */
	aiToolResult: (conversationId: string, toolCallId: string, result: AiToolResultInput) => __TAURI_INVOKE<AiEntryView>("ai_tool_result", { conversationId, toolCallId, result }),
	/**
	 *  Runs a tool that runs in Rust (`run_command` on `session_id`, `web_search`, `fetch_url`,
	 *  `read_skill`, MCP tools) and stores its result.
	 */
	aiToolRun: (conversationId: string, toolCallId: string, sessionId: string | null, editedArguments: string | null) => __TAURI_INVOKE<AiEntryView>("ai_tool_run", { conversationId, toolCallId, sessionId, editedArguments }),
	/**  Stops the turn: aborts the request and running tools, cancels calls without a result. */
	aiStop: (conversationId: string) => __TAURI_INVOKE<null>("ai_stop", { conversationId }),
	/**  AI-21: summarizes the context with the given model and moves `context_start` to the summary. */
	aiCompact: (conversationId: string, context: AiTurnContext) => __TAURI_INVOKE<AiEntryView>("ai_compact", { conversationId, context }),
	/**  AI-24: conversations whose title or message text contains `query`, ignoring case. */
	aiSearch: (query: string) => __TAURI_INVOKE<AiSearchHit[]>("ai_search", { query }),
	/**
	 *  AI-26: replaces the user's message `entry_id` with `text`, deletes every entry after it, and
	 *  starts a turn whose events stream on `channel`, like `ai_send`.
	 */
	aiEditResend: (conversationId: string, entryId: string, text: string, context: AiTurnContext, channel: Channel<AiTurnEvent>) => __TAURI_INVOKE<AiSendStarted>("ai_edit_resend", { conversationId, entryId, text, context, channel }),
	/**
	 *  AI-35: text files dropped on the panel in the desktop app, whose webview hands the WebView
	 *  only their paths. Reads only paths of the window's last drop, each once
	 *  (`crate::dropped`); with any other path, nothing is read. One result per path, in order,
	 *  naming the file by its base name. The per-message total stays the panel's to check.
	 */
	aiReadDroppedFiles: (paths: string[]) => __TAURI_INVOKE<DroppedFile[]>("ai_read_dropped_files", { paths }),
	skillsList: () => __TAURI_INVOKE<SkillView[]>("skills_list"),
	skillGet: (id: string) => __TAURI_INVOKE<SkillDetail>("skill_get", { id }),
	/**  The built-in `hatoba` skill (AI-34), with this app's version, for the viewer in Settings. */
	skillBuiltinGet: () => __TAURI_INVOKE<BuiltinSkillView>("skill_builtin_get"),
	/**  Validates like an import (AI-27); rejects with `invalid_input` naming the field. */
	skillSave: (input: SkillInput) => __TAURI_INVOKE<SkillView>("skill_save", { input }),
	skillDelete: (id: string) => __TAURI_INVOKE<null>("skill_delete", { id }),
	skillSetEnabled: (id: string, enabled: boolean) => __TAURI_INVOKE<null>("skill_set_enabled", { id, enabled }),
	/**  Reads a folder or `.zip` the user picked; nothing is saved. */
	skillImportPreview: (path: string) => __TAURI_INVOKE<SkillImportPreview>("skill_import_preview", { path }),
	/**
	 *  Imports what the preview showed: reads the path again and refuses it when it no longer
	 *  matches the preview's `token`. `replace_id` replaces that skill; `rename` saves it under a
	 *  new name.
	 */
	skillImport: (path: string, token: string, replaceId: string | null, rename: string | null) => __TAURI_INVOKE<SkillView>("skill_import", { path, token, replaceId, rename }),
	/**  Writes the skill as a `.zip` to a path the user picked. */
	skillExport: (id: string, path: string) => __TAURI_INVOKE<null>("skill_export", { id, path }),
	mcpServersList: () => __TAURI_INVOKE<McpServerView[]>("mcp_servers_list"),
	/**  Saves a server; a running one restarts when its name or transport changed. */
	mcpServerSave: (input: McpServerInput) => __TAURI_INVOKE<McpServerView>("mcp_server_save", { input }),
	mcpServerDelete: (id: string) => __TAURI_INVOKE<null>("mcp_server_delete", { id }),
	/**  On this device only (AI-29). Disabling stops a running server. */
	mcpServerSetEnabled: (id: string, enabled: boolean) => __TAURI_INVOKE<null>("mcp_server_set_enabled", { id, enabled }),
	mcpServerStatus: (id: string) => __TAURI_INVOKE<McpServerStatus>("mcp_server_status", { id }),
	/**  Starts (or restarts) the server now and lists its tools. */
	mcpServerStart: (id: string) => __TAURI_INVOKE<McpServerStatus>("mcp_server_start", { id }),
	mcpServerStop: (id: string) => __TAURI_INVOKE<null>("mcp_server_stop", { id }),
	/**
	 *  AI-31 Always allow on this device: one tool (the server's own name), or every tool with `tool`
	 *  null.
	 */
	mcpSetAlwaysAllow: (serverId: string, tool: string | null, allow: boolean) => __TAURI_INVOKE<null>("mcp_set_always_allow", { serverId, tool, allow }),
	/**
	 *  The MCP tool behind a name the model called in the conversation: from the offer of the
	 *  conversation's latest request, as `ai_tool_run` resolves it, else from the running servers.
	 *  Null when neither has it, or its server was deleted; the panel then asks in either mode.
	 */
	mcpToolInfo: (conversationId: string, name: string) => __TAURI_INVOKE<{
	server_id: string,
	server_name: string,
	always_ask: boolean,
	tool: McpToolView,
} | null>("mcp_tool_info", { conversationId, name }),
	/**  AI-33: what pasted `mcpServers` / VS Code `servers` JSON would add. */
	mcpImportPreview: (json: string) => __TAURI_INVOKE<McpImportPreview>("mcp_import_preview", { json }),
	/**  Adds every importable server; env and header values move into the vault. */
	mcpImport: (json: string) => __TAURI_INVOKE<McpServerView[]>("mcp_import", { json }),
	/**  `mcpServers` JSON with placeholders in place of env and header values. */
	mcpExport: () => __TAURI_INVOKE<string>("mcp_export"),
};

/** Events */
export const events = {
	aiMcpStatus: makeEvent<McpServerStatus>("ai://mcp-status"),
	sshAuthPrompt: makeEvent<AuthPrompt>("ssh://auth-prompt"),
	sshForward: makeEvent<ForwardStatusEvent>("ssh://forward"),
	sshHostkeyPrompt: makeEvent<HostKeyPrompt>("ssh://hostkey-prompt"),
	sshState: makeEvent<SessionStateEvent>("ssh://state"),
	syncStatus: makeEvent<SyncStatus>("sync://status"),
	transferProgress: makeEvent<TransferProgressEvent>("transfer://progress"),
	vaultLocked: makeEvent<VaultLockedEvent>("vault://locked"),
};

/* Types */
export type AiAuthHeader = "x-api-key" | "authorization";

export type AiConversationDetail = {
	conversation: AiConversationView,
	entries: AiEntryView[],
	/**  A turn of this conversation is running (its events go to the channel that started it). */
	running: boolean,
};

export type AiConversationView = {
	id: string,
	title: string,
	/**  The host the conversation last worked on. */
	host_id: string | null,
	pinned: boolean,
	/**  `entry_id` where the context sent to the model starts (AI-21). */
	context_start: string | null,
	/**  The thinking level its last message was sent with (AI-05); `None` is Default. */
	effort: AiEffort | null,
	created_at: number,
	updated_at: number,
	/**  The newest entry or conversation change, for sorting history (AI-23). */
	last_activity: number,
};

/**  A thinking level (AI-05), lowest first. Where one is optional, `None` is Default. */
export type AiEffort = "low" | "medium" | "high" | "xhigh" | "max";

/**  A stored conversation entry (§13.7), without the provider's raw message. */
export type AiEntryView = { role: "user"; entry_id: string; created_at: number; text: string } | { role: "assistant"; entry_id: string; created_at: number; provider_id: string; model_id: string; text: string; reasoning: string | null; tool_calls: AiToolCall[]; finish: AiFinish; usage: AiUsage | null } | { role: "tool"; entry_id: string; created_at: number; tool_call_id: string; status: AiToolStatus; content: string } | { role: "summary"; entry_id: string; created_at: number; text: string };

export type AiFinish = "stop" | "tool_calls" | "length" | "refused";

/**  A model of a provider (AI-03). Token limits are `None` when unknown. */
export type AiModel = {
	id: string,
	name: string,
	context_window: number | null,
	max_output_tokens: number | null,
	/**
	 *  The thinking levels the model accepts, lowest first (AI-05); empty for none, `None` when
	 *  unknown (the panel then offers Low to High).
	 */
	efforts: AiEffort[] | null,
	/**  Whether the model supports adaptive thinking (Anthropic's model list), `None` when unknown. */
	adaptive_thinking: boolean | null,
};

export type AiModelRef = {
	provider_id: string,
	model_id: string,
};

export type AiPermissionMode = "manual" | "bypass";

export type AiProtocol = "chat_completions" | "anthropic";

export type AiProviderInput = {
	/**  `None` creates a provider. With an id, a `None` key keeps (or tests with) the saved one. */
	id: string | null,
	name: string,
	protocol: AiProtocol,
	base_url: string,
	/**  `None` keeps the saved key (as HOST-08 does for passwords); `""` clears it. */
	api_key: string | null,
	auth_header: AiAuthHeader,
	models: AiModel[],
};

/**  AI-01. The API key never reaches the WebView: only whether one is saved. */
export type AiProviderView = {
	id: string,
	name: string,
	protocol: AiProtocol,
	base_url: string,
	has_api_key: boolean,
	/**  Only used by `anthropic`. */
	auth_header: AiAuthHeader,
	models: AiModel[],
	updated_at: number,
};

export type AiSearchHit = {
	conversation_id: string,
	/**  The first matching entry, or `None` when only the title matched. */
	entry_id: string | null,
	/**  Text around the first match. */
	snippet: string,
};

export type AiSendInput = {
	/**  `None` starts a new conversation, stored with this first message (AI-07). */
	conversation_id: string | null,
	text: string,
	context: AiTurnContext,
};

export type AiSendStarted = {
	conversation: AiConversationView,
	user_entry: AiEntryView,
};

/**  The synced `Settings.ai` (§5.1). */
export type AiSettingsView = {
	default_model: AiModelRef | null,
	/**  The thinking level new conversations start with (AI-05); `None` is Default. */
	default_effort: AiEffort | null,
	search_provider_id: string | null,
	/**  The built-in `hatoba` skill is offered (AI-34). */
	builtin_skill_enabled: boolean,
	/**  Sent with every request, at most 4,000 characters (AI-36). */
	custom_instructions: string,
};

/**  AI-04 Test Connection, also used for the search provider test. */
export type AiTestFailure = "auth" | "network" | "unknown_model" | "invalid_url" | "other";

export type AiTestResult = {
	ok: boolean,
	failure: AiTestFailure | null,
	status: number | null,
	/**  The provider's own message, when it sent one. */
	message: string | null,
};

export type AiToolCall = {
	id: string,
	name: string,
	/**  JSON text. */
	arguments: string,
};

/**  A result the frontend produced: `read_terminal`, `send_input`, or a rejection (AI-17). */
export type AiToolResultInput = {
	status: AiToolStatus,
	content: string,
	/**  AI-17 Edit: the arguments the user changed the call to, so the result tells the model. */
	edited_arguments: string | null,
};

export type AiToolStatus = "ok" | "error" | "rejected" | "cancelled";

/**  What a request is made with. The frontend owns the tab, so it says what the turn may act on. */
export type AiTurnContext = {
	provider_id: string,
	model_id: string,
	/**
	 *  The thinking level (AI-05); `None` is Default. Requests send the highest level the model
	 *  offers that is not above it, and the conversation keeps it for its next message.
	 */
	effort: AiEffort | null,
	/**  The tab's host; the next message moves the conversation to it (AI-09). */
	host_id: string | null,
	/**
	 *  The tab's quick-connect target when it has no saved host (HOST-12): the next message
	 *  moves the conversation off its saved host, and the request names the target instead.
	 */
	target: QuickTarget | null,
	/**  A connected terminal tab is attached; `false` offers no terminal tools (AI-09). */
	tab: boolean,
	/**
	 *  The tab's SSH session while it is connected, whose server's identification string the
	 *  system prompt states (§13.1).
	 */
	session_id: string | null,
	/**  MCP servers switched off for this conversation (AI-30, P2). */
	disabled_mcp_servers: string[],
};

export type AiTurnEndReason = "completed" | "length" | "refused" | "stopped" | "error";

/**  Streamed on the channel of `ai_send` / `ai_retry` for the whole turn (§13.1). */
export type AiTurnEvent = { kind: "request_started" } | { kind: "text"; delta: string } | { kind: "reasoning"; delta: string } | { kind: "tool_call"; id: string; name: string; arguments: string } | { kind: "usage"; input_tokens: number; output_tokens: number; estimated: boolean } | 
/**  An entry was stored: the assistant response, a tool result, or a cancelled result. */
{ kind: "entry"; entry: AiEntryView } | 
/**  One response finished. With `tool_calls`, Rust waits for every call's result. */
{ kind: "done"; finish: AiFinish } | { kind: "error"; status: number | null; message: string } | 
/**
 *  The provider refused the thinking level, so the request was sent again without it and the
 *  model answers at its default depth (AI-05).
 */
{ kind: "effort_ignored" } | { kind: "turn_ended"; reason: AiTurnEndReason };

export type AiUsage = {
	input_tokens: number,
	output_tokens: number,
	estimated: boolean,
};

export type AppError = {
	code: ErrorCode,
	detail: string,
	retry_at: number | null,
	field: string | null,
	ssh_kind: SshErrorKind | null,
	key_kind: KeyParseErrorKind | null,
	permission: CloudflarePermission | null,
	cf_code: number | null,
	/**  `ai`: the HTTP status the provider answered with. */
	http_status: number | null,
};

export type AppInfo = {
	version: string,
	platform: Platform,
	mica: boolean,
};

export type Appearance = "system" | "light" | "dark";

export type AuthKind = "password" | "key" | "agent" | "ask";

export type AuthPrompt = {
	request_id: string,
	session_id: string | null,
	name: string,
	instructions: string,
	prompts: AuthPromptField[],
	/**
	 *  The login password of a quick connection (HOST-12), asked like an "ask every time"
	 *  password (SSH-03) rather than as a server prompt; answered with one value.
	 */
	password: boolean,
	/**  `user@host:port` of the hop that asks. */
	target: string,
};

export type AuthPromptField = {
	prompt: string,
	echo: boolean,
};

/**  A newer release that `update_install` can download and install. */
export type AvailableUpdate = {
	version: string,
	/**  The release notes in Markdown. */
	notes: string | null,
	/**  When the release was published, Unix ms. */
	published_at: number | null,
	/**  The release page on GitHub. */
	release_url: string,
};

/**  The built-in `hatoba` skill (AI-34), read-only. */
export type BuiltinSkillView = {
	name: string,
	description: string,
	/**  `Settings.ai.builtin_skill_enabled`. */
	enabled: boolean,
	/**  `SKILL.md` without its frontmatter, with the app's version filled in. */
	body: string,
	/**  The files besides `SKILL.md`, sorted by path. */
	files: SkillFileView[],
};

export type CloudflareAccount = {
	id: string,
	name: string,
};

export type CloudflarePermission = "workers_scripts" | "d1";

export type ConflictAction = "keep" | "restore";

export type ConflictField = {
	field: string,
	local: string | null,
	remote: string | null,
};

export type ConflictResolution = "local_won" | "remote_won" | "kept_both" | "modified_won";

export type ConflictView = {
	id: number,
	item_id: string,
	item_type: ItemType,
	item_name: string,
	resolution: ConflictResolution,
	local_updated_at: number | null,
	remote_updated_at: number | null,
	local_deleted: boolean,
	remote_deleted: boolean,
	fields: ConflictField[],
	created_at: number,
};

export type ConnectOptions = {
	cols: number,
	rows: number,
	/**  `ask` auth (SSH-03): used once, never stored. */
	password: string | null,
	passphrase: string | null,
};

export type CursorChoice = "block" | "bar" | "underline";

export type D1Database = {
	id: string,
	name: string,
	region: string | null,
};

export type Density = "regular" | "compact";

export type DeployDatabaseAction = "create" | 
/**  An existing database with nothing but Hatoba's migrations. */
"use" | 
/**  The database already bound to the Hatoba Worker. */
"bound";

export type DeployOutcome = {
	url: string,
	/**  `false`: the Worker has not answered yet (step 8 is waiting); `deploy_check` asks again. */
	ready: boolean,
};

/**  What step 2 found, shown before anything is written. */
export type DeployPlan = {
	/**  The account's workers.dev subdomain; `None` means the user has to choose one. */
	subdomain: string | null,
	worker: DeployWorkerAction,
	database: DeployDatabaseAction | null,
	database_name: string | null,
};

/**  Sent on the `deploy_run` channel as each step starts and ends. */
export type DeployProgress = {
	step: DeployStep,
	status: DeployStepStatus,
};

/**  Step 1 passed. Later calls name the deployment by `handle`; the API token stays in Rust. */
export type DeployStart = {
	handle: string,
	/**  The token belongs to the account given with it rather than to a user. */
	account_owned: boolean,
	/**  The accounts a user token reaches; empty when the user has to enter the account ID. */
	accounts: CloudflareAccount[],
	/**  The default Worker and database names. */
	worker_name: string,
	database_name: string,
};

export type DeployStep = "verify" | "inspect" | "create_database" | "migrate" | "upload" | "setup_token" | "route" | "wait";

export type DeployStepStatus = "running" | "done" | "skipped";

export type DeployTarget = {
	account_id: string,
	worker_name: string,
	database_name: string,
	/**  The workers.dev subdomain to create when the account has none. */
	subdomain: string | null,
};

export type DeployWorkerAction = "create" | "update" | 
/**  A Hatoba Worker whose database holds a vault: the deployment stops. */
"has_vault" | 
/**  A Worker the app does not recognize: the deployment stops. */
"foreign";

export type DeviceView = {
	device_id: string,
	name: string,
	platform: string,
	created_at: number,
	last_seen: number,
	current: boolean,
};

/**
 *  A text file dropped on the AI panel (AI-35), named by its base name only, never its path (a
 *  path can name the local user).
 */
export type DroppedFile = { status: "ok"; name: string; text: string } | { status: "refused"; name: string; reason: DroppedFileRefusal };

/**  Why a file dropped on the AI panel is not attached (AI-35): the panel's own reasons. */
export type DroppedFileRefusal = 
/**  An image, which attachments do not take yet. */
"image" | 
/**  Over 256 KB. */
"too_large" | 
/**  NUL bytes or invalid UTF-8. */
"binary" | 
/**  Not a file, gone, or not readable. */
"unreadable";

export type ErrorCode = "locked" | "not_initialized" | "already_initialized" | "wrong_password" | "wrong_recovery_code" | "throttled" | "not_found" | "invalid_input" | "key_parse" | "ssh" | "sftp" | "sync" | "sync_auth" | "sync_offline" | "remote_initialized" | "remote_not_initialized" | 
/**  In-app deployment (§6.7): Cloudflare rejected the API token. */
"cloudflare_token" | 
/**  The API token lacks the permission in `permission`. */
"cloudflare_permission" | 
/**  Any other Cloudflare API failure; `cf_code` has Cloudflare's code when it sent one. */
"cloudflare" | "subdomain_required" | "subdomain_unavailable" | "worker_name_taken" | 
/**  An upgrade found no Hatoba Worker with a vault under the name. */
"worker_not_found" | 
/**  An upgrade found a Worker newer than the one this build deploys. */
"worker_newer" | 
/**  This build does not embed the Worker, so it cannot deploy it. */
"no_worker_bundle" | 
/**
 *  AI assistant (§13): a model provider or search provider failed. `http_status` has the
 *  status it answered with, when it answered; `detail` is its own message.
 */
"ai" | 
/**  A downloaded update does not carry a valid signature from the release key (spec §11). */
"update_signature" | "cancelled" | "io" | "internal";

export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	is_symlink: boolean,
	size: number,
	modified: number | null,
	permissions: string,
};

export type ForwardInput = {
	id: string | null,
	host_id: string,
	bind_address: string,
	bind_port: number,
	dest_host: string,
	dest_port: number,
	auto_start: boolean,
};

export type ForwardState = "running" | "stopped" | "failed";

/**  A forward's state on one live session. */
export type ForwardStatusEvent = {
	session_id: string,
	forward_id: string,
	state: ForwardState,
	/**  The actually bound local port (differs from `bind_port` when it was 0). */
	local_port: number | null,
	error: string | null,
};

/**  A saved local (`-L`) forward. Remote and dynamic forwards are P2. */
export type ForwardView = {
	id: string,
	host_id: string,
	bind_address: string,
	bind_port: number,
	dest_host: string,
	dest_port: number,
	auto_start: boolean,
};

export type GenerateAlgorithm = "ed25519" | "rsa";

export type GroupInput = {
	id: string | null,
	name: string,
	parent_id: string | null,
	sort: number,
};

export type GroupView = {
	id: string,
	name: string,
	parent_id: string | null,
	sort: number,
};

/**  One of a host's environment variables (SSH-14). */
export type HostEnvVar = {
	name: string,
	value: string,
};

export type HostInput = {
	id: string | null,
	name: string,
	address: string,
	port: number,
	username: string,
	auth_kind: AuthKind,
	/**  `None` keeps the saved password (HOST-08). */
	password: string | null,
	key_id: string | null,
	group_id: string | null,
	tags: string[],
	favorite: boolean,
	jump_host_id: string | null,
	note: string,
	/**  At most 2,000 characters (AI-37). */
	ai_notes: string,
	/**  Names are trimmed; see `hatoba_core::model::check_host_env` for the rules (SSH-14). */
	env: HostEnvVar[],
};

export type HostKeyPrompt = {
	request_id: string,
	session_id: string | null,
	host: string,
	port: number,
	key_type: string,
	fingerprint: string,
	kind: HostKeyPromptKind,
	known_fingerprint: string | null,
	known_key_type: string | null,
};

export type HostKeyPromptKind = "new" | "changed";

export type HostView = {
	id: string,
	name: string,
	address: string,
	port: number,
	username: string,
	auth_kind: AuthKind,
	has_password: boolean,
	key_id: string | null,
	group_id: string | null,
	tags: string[],
	favorite: boolean,
	jump_host_id: string | null,
	note: string,
	/**  What the AI assistant is told about the host (AI-37). */
	ai_notes: string,
	updated_at: number,
	last_connected_at: number | null,
	/**
	 *  The server's operating system from its SSH identification string on the last connection
	 *  from this device, such as `ubuntu` (HOST-11). Device-local, like `last_connected_at`.
	 */
	os: string | null,
	/**
	 *  The host's terminals show the server's resource usage on this device (TERM-12).
	 *  Device-local, like `last_connected_at`, and off until turned on.
	 */
	show_stats: boolean,
	/**  Environment variables the terminal asks the server to set (SSH-14). */
	env: HostEnvVar[],
};

export type ImportResult = {
	hosts_created: number,
	keys_imported: number,
	warnings: string[],
};

export type ItemType = "host" | "group" | "key" | "known_host" | "forward" | "snippet" | "ai_provider" | "search_provider" | "ai_conversation" | "ai_message" | "skill" | "skill_file" | "mcp_server" | "settings";

export type KeyAlgorithm = "ed25519" | "ecdsa" | "rsa";

export type KeyGenerateInput = {
	name: string,
	algorithm: GenerateAlgorithm,
	comment: string,
	passphrase: string | null,
};

export type KeyImportInput = {
	name: string,
	private_key: string | null,
	path: string | null,
	passphrase: string | null,
};

export type KeyParseErrorKind = "unsupported_format" | "passphrase_required" | "wrong_passphrase" | "unsupported_algorithm" | "invalid";

export type KeyView = {
	id: string,
	name: string,
	algorithm: KeyAlgorithm,
	bits: number,
	public_key: string,
	fingerprint: string,
	comment: string,
	has_passphrase: boolean,
	created_at: number,
	updated_at: number,
	used_by: string[],
};

export type Language = "system" | "zh-CN" | "en" | "ja";

/**  Device-local UI preferences (readable while locked; never synced). */
export type LocalPrefs = {
	language: Language,
	appearance: Appearance,
	density: Density,
	host_probe: boolean,
	/**
	 *  Check GitHub for a newer release once after unlock. Off by default: no request leaves
	 *  the device unless the user asks for it (spec §11, no telemetry).
	 */
	auto_update_check: boolean,
	/**  AI-16: the permission mode new conversations start in on this device. */
	ai_permission_mode: AiPermissionMode,
	/**  AI-16: the user confirmed the first switch to bypass on this device. */
	ai_bypass_confirmed: boolean,
	/**  AI-18: a turn pauses after this many tool calls. */
	ai_tool_call_limit: number,
	/**  The AI panel is open (§9). */
	ai_panel_open: boolean,
	/**  The AI panel's width in CSS pixels. */
	ai_panel_width: number,
};

export type LockReason = "manual" | "idle" | "sleep";

export type McpImportPreview = {
	servers: McpImportServer[],
	/**  Entries that cannot be imported, such as an `sse` server, with the reason. */
	skipped: McpImportSkipped[],
};

export type McpImportServer = {
	name: string,
	transport: McpTransportView,
	/**  A saved server has this name; the import adds a numeric suffix. */
	exists: boolean,
};

export type McpImportSkipped = {
	name: string,
	reason: string,
};

export type McpSecretInput = {
	key: string,
	/**  `None` keeps the saved value for this key. */
	value: string | null,
};

export type McpServerInput = {
	/**  `None` creates a server. */
	id: string | null,
	name: string,
	transport: McpTransportInput,
	always_ask: boolean,
};

export type McpServerState = "stopped" | "starting" | "running" | "failed";

/**
 *  A server's live state (AI-32), also pushed as `ai://mcp-status` on every change. The stderr
 *  lines stay in memory and are never logged.
 */
export type McpServerStatus = {
	server_id: string,
	state: McpServerState,
	error: string | null,
	/**  The last stderr lines of a `stdio` server, kept in memory only (AI-32). */
	stderr: string[],
	/**  The tools from the last successful listing. */
	tools: McpToolView[],
};

export type McpServerView = {
	id: string,
	name: string,
	transport: McpTransportView,
	/**  Ask even in bypass mode. Synced (AI-31). */
	always_ask: boolean,
	/**  Enabled on this device; a server from another device starts enabled only for `http`. */
	enabled: boolean,
	/**  On this device, every tool of the server runs without asking in manual mode (AI-31). */
	always_allow: boolean,
	/**  On this device, these tools (the server's own names) run without asking in manual mode. */
	always_allow_tools: string[],
	updated_at: number,
};

/**  Shown on the approval card; never changes whether a call asks (AI-31). */
export type McpToolAnnotations = {
	title: string | null,
	read_only_hint: boolean | null,
	destructive_hint: boolean | null,
	idempotent_hint: boolean | null,
	open_world_hint: boolean | null,
};

/**  The MCP tool behind a name the model called, for the approval card (AI-31). */
export type McpToolInfo = {
	server_id: string,
	server_name: string,
	always_ask: boolean,
	tool: McpToolView,
};

export type McpToolView = {
	/**  The name offered to the model, `mcp__<server>__<tool>` after cleaning (AI-30). */
	name: string,
	/**  The server's own tool name. */
	tool: string,
	description: string,
	annotations: McpToolAnnotations,
	/**  Always allow on this device (per tool, or because the whole server is). */
	always_allow: boolean,
};

export type McpTransportInput = { kind: "stdio"; command: string; args: string[]; env: McpSecretInput[] } | { kind: "http"; url: string; headers: McpSecretInput[] };

export type McpTransportView = { kind: "stdio"; command: string; args: string[]; env_keys: string[] } | { kind: "http"; url: string; header_keys: string[] };

export type Platform = "windows" | "macos" | "linux";

export type ProbeResult = {
	id: string,
	online: boolean,
	latency_ms: number | null,
};

/**
 *  A target typed into the hosts search field (quick connect, HOST-12). It is never saved as a
 *  host; once connected it joins the device-local recent list.
 */
export type QuickTarget = {
	/**  DNS name or IP address, IPv6 without brackets. */
	address: string,
	port: number,
	username: string,
};

export type RightClick = "copy_paste" | "menu";

export type SearchKind = "brave" | "tavily" | "searxng";

export type SearchProviderInput = {
	id: string | null,
	kind: SearchKind,
	base_url: string | null,
	/**  `None` keeps the saved key; `""` clears it. */
	api_key: string | null,
};

/**  The backend of `web_search` (AI-14). */
export type SearchProviderView = {
	id: string,
	kind: SearchKind,
	/**  The instance URL for SearXNG, `None` otherwise. */
	base_url: string | null,
	has_api_key: boolean,
	updated_at: number,
};

/**
 *  One reading of a server's resource usage (TERM-12). Sizes are in bytes and rates in bytes
 *  per second; what the server did not report is `None`.
 */
export type ServerStatsView = {
	/**  Busy share of all CPUs since the previous reading, 0 to 100; `None` in the first one. */
	cpu_percent: number | null,
	cpus: number | null,
	/**  Load averages over 1, 5 and 15 minutes. */
	load: [(number | null), (number | null), (number | null)] | null,
	mem_total: number | null,
	/**  The total less what the kernel counts as available. */
	mem_used: number | null,
	/**  Zero when the server has no swap. */
	swap_total: number | null,
	swap_used: number | null,
	net_rx_rate: number | null,
	net_tx_rate: number | null,
	/**  The interfaces the rates count: those of the default routes, or else all but loopback. */
	net_interfaces: string[],
	/**  The root filesystem. */
	disk_total: number | null,
	disk_used: number | null,
	/**  Space left for unprivileged users, as `df` counts it. */
	disk_available: number | null,
	uptime_secs: number | null,
};

export type SessionState = "connecting" | "connected" | "disconnected" | "failed";

export type SessionStateEvent = {
	session_id: string,
	/**  `None` for a quick-connect session (HOST-12). */
	host_id: string | null,
	state: SessionState,
	latency_ms: number | null,
	error: AppError | null,
	exit_status: number | null,
};

export type SettingsView = {
	terminal: TerminalSettings,
	auto_lock_minutes: number,
	lock_disconnects_sessions: boolean,
};

export type SkillDetail = {
	skill: SkillView,
	/**  `SKILL.md` without its frontmatter. */
	body: string,
	files: SkillFileView[],
	/**  Other frontmatter fields, kept for export. They change nothing (AI-27). */
	frontmatter_keys: string[],
};

export type SkillFileView = {
	/**  Relative path with forward slashes, such as `references/nginx.md`. Never `SKILL.md`. */
	path: string,
	content: string,
};

/**  What an import would save, shown before saving (AI-27). Importable when `issues` is empty. */
export type SkillImportPreview = {
	/**  `None` when `SKILL.md` is missing or unreadable. */
	name: string | null,
	description: string | null,
	body: string | null,
	files: SkillFileView[],
	frontmatter_keys: string[],
	/**  Files that are not UTF-8 text, which the import skips. */
	skipped: string[],
	issues: SkillIssue[],
	/**  A saved skill with the same name, which the user may replace (or rename the new one). */
	existing_id: string | null,
	/**  The name is the built-in skill's (AI-34): the skill can be imported only under another. */
	reserved_name: boolean,
	/**
	 *  A digest of what was read, which `skill_import` takes back: it imports the source only if
	 *  it still reads the same, so what is saved is what this preview showed.
	 */
	token: string,
};

export type SkillInput = {
	/**  `None` creates a skill. */
	id: string | null,
	name: string,
	description: string,
	enabled: boolean,
	body: string,
	/**  Every file besides `SKILL.md`; a saved file left out is deleted. */
	files: SkillFileView[],
};

/**  Why a skill cannot be imported or saved (AI-27). */
export type SkillIssue = { kind: "missing_skill_md" } | { kind: "invalid_frontmatter"; detail: string } | { kind: "invalid_name"; name: string } | { kind: "missing_description" } | { kind: "description_too_long"; chars: number } | { kind: "file_too_large"; path: string; size: number } | { kind: "unsafe_path"; path: string } | { kind: "too_many_files"; count: number } | 
/**  More than 5 MB in total. */
{ kind: "too_large"; bytes: number };

export type SkillView = {
	id: string,
	name: string,
	description: string,
	enabled: boolean,
	/**  Paths of the files besides `SKILL.md`, sorted. */
	files: string[],
	updated_at: number,
};

export type SshConfigCandidate = {
	alias: string,
	address: string,
	port: number,
	username: string,
	identity_file: string | null,
	proxy_jump: string | null,
	exists: boolean,
};

export type SshErrorKind = "dns" | "refused" | "timeout" | "unreachable" | "auth_failed" | "host_key_rejected" | "key_parse" | "disconnected" | "protocol" | "io" | "channel" | "sftp" | "cancelled" | "other";

/**  Device-local state of the sidebar's GitHub star prompt (spec §9; never synced). */
export type StarPrompt = {
	/**  When this device first read the state, Unix ms. The prompt waits a day from then. */
	first_seen_at: number,
	/**  The user starred the repository, opened the bug report form, or closed the prompt. */
	done: boolean,
};

/**  Streamed on the channel of `ssh_stats_start` (TERM-12). */
export type StatsEvent = 
/**  A reading, one per interval. */
{ kind: "stats"; stats: ServerStatsView } | 
/**
 *  The server does not run Linux; the last event. `system` is its name, such as `FreeBSD`,
 *  or empty when unknown.
 */
{ kind: "unsupported"; system: string } | 
/**  Sampling stopped on its own (the script failed or the connection ended); the last event. */
{ kind: "ended"; error: AppError };

export type SyncConfigInput = { kind: "worker"; url: string; setup_token: string | null } | { kind: "d1"; account_id: string; database_id: string; api_token: string };

export type SyncCounts = {
	hosts: number,
	keys: number,
	groups: number,
};

export type SyncKind = "none" | "worker" | "d1";

export type SyncState = "off" | "idle" | "syncing" | "offline" | "auth_failed" | "error" | 
/**  The Worker's version stops sync until it or the app is updated; `worker_update` says which. */
"paused";

export type SyncStatus = {
	kind: SyncKind,
	endpoint: string | null,
	database: string | null,
	state: SyncState,
	last_synced_at: number | null,
	pending: number,
	conflicts: number,
	auto_sync: boolean,
	message: string | null,
	counts: SyncCounts | null,
	/**
	 *  Worker mode: how the Worker's `/v1/health` compares with this build (§6.7, Upgrades).
	 *  `None` when there is nothing to show, including a dismissed "update available".
	 */
	worker_update: WorkerUpdate | null,
};

export type SyncTestResult = {
	ok: boolean,
	initialized: boolean,
	version: string | null,
	latency_ms: number | null,
	databases: D1Database[] | null,
	error: AppError | null,
};

export type TagCount = {
	name: string,
	count: number,
};

/**
 *  One terminal frame on the per-session channel: tag byte + payload. Sent through Tauri's raw
 *  binary IPC path (an `ArrayBuffer` in the WebView), never as a JSON number array (§10.3).
 */
export type TermFrame = number[];

export type TerminalSettings = {
	font_family: string,
	font_size: number,
	theme: ThemeChoice,
	cursor_style: CursorChoice,
	scrollback: number,
	right_click: RightClick,
	confirm_multiline_paste: boolean,
};

export type TestResult = {
	ok: boolean,
	latency_ms: number | null,
	host_key_verified: boolean,
	error: AppError | null,
};

export type ThemeChoice = "system" | "light" | "dark";

export type TransferDirection = "upload" | "download";

export type TransferProgressEvent = {
	transfer_id: string,
	session_id: string,
	direction: TransferDirection,
	name: string,
	bytes: number,
	total: number,
	bytes_per_sec: number,
	state: TransferState,
	error: string | null,
};

export type TransferState = "running" | "done" | "failed" | "cancelled";

/**  What the update check found (spec §11). */
export type UpdateCheck = {
	current_version: string,
	/**  A release newer than the running version, or `None` when there is none. */
	update: AvailableUpdate | null,
};

/**  Sent on the `update_install` channel. */
export type UpdateProgress = 
/**  Bytes downloaded so far, and the installer's size when the server sent it. */
{ kind: "downloading"; downloaded: number; total: number | null } | 
/**  The download passed the signature check. Hatoba closes, and the installer starts it again. */
{ kind: "installing" };

/**  What the "Update Worker" form starts from (§6.7, Upgrades). */
export type UpgradeDefaults = {
	/**  The Worker URL in the sync settings. */
	url: string,
	/**  The account ID, when the app deployed the Worker. */
	account_id: string | null,
	/**
	 *  The Worker name: recorded when the app deployed it, or the first label of a workers.dev
	 *  URL. `None` for a custom domain, where the user enters it.
	 */
	worker_name: string | null,
	/**
	 *  The app deployed the Worker. Otherwise it may have come from the Deploy to Cloudflare
	 *  button, whose next push from the user's repository replaces the upgrade.
	 */
	deployed_by_app: boolean,
};

/**  What step 2 of an upgrade found, shown before anything is written. */
export type UpgradePlan = {
	worker: UpgradeWorkerAction,
	/**  The database bound to the Worker. */
	database_name: string | null,
	/**  Migrations step 4 applies. */
	migrations: number,
	/**  Step 7 runs: the Worker URL is its workers.dev URL. */
	route: boolean,
	/**  The version the Worker URL reports, when it answers. */
	version: string | null,
	/**  The version the upgrade deploys. */
	bundled: string,
};

export type UpgradeTarget = {
	account_id: string,
	worker_name: string,
};

export type UpgradeWorkerAction = "upgrade" | 
/**  No Worker has the name: the upgrade stops. */
"missing" | 
/**  A Worker the app does not recognize: the upgrade stops. */
"foreign" | 
/**  A Hatoba Worker without a vault: the upgrade stops. */
"no_vault" | 
/**  The Worker is newer than the bundled version: the upgrade stops. */
"newer";

export type VaultLockedEvent = {
	reason: LockReason,
};

export type VaultState = "uninitialized" | "locked" | "unlocked";

export type VaultStatus = {
	state: VaultState,
	failed_attempts: number,
	retry_at: number | null,
	sync_kind: SyncKind,
	biometric_available: boolean,
	biometric_enabled: boolean,
};

export type WorkerUpdate = {
	kind: WorkerUpdateKind,
	/**  The version the Worker reports. */
	version: string,
	/**  The version "Update Worker" deploys; `None` in builds without the Worker bundle. */
	bundled: string | null,
};

export type WorkerUpdateKind = 
/**  Older than the bundled version: sync continues, and the update can be dismissed. */
"available" | 
/**  Older than the minimum version, or a lower `api`: sync is paused. */
"required" | 
/**  A newer `api` than this app speaks: sync is paused until Hatoba is updated. */
"app_required";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

