// Generated by tauri-specta from src-tauri. Do not edit.
// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Opens the Windows 11 Snap Layouts flyout (hovering the custom maximize button, WIN-01). */
	windowSnapOverlay: () => __TAURI_INVOKE<void>("window_snap_overlay"),
	/**  Writes text to a path the user chose in the native save dialog (recovery code "Save as Text"). */
	saveTextFile: (path: string, contents: string) => __TAURI_INVOKE<null>("save_text_file", { path, contents }),
	/**  Feeds the idle auto-lock timer (SEC-02). */
	activityPing: () => __TAURI_INVOKE<void>("activity_ping"),
	/**
	 *  Asks GitHub Releases whether a newer version exists (Settings → About). Runs only when the
	 *  user checks, or after unlock when they turned on the automatic check.
	 */
	updateCheck: () => __TAURI_INVOKE<UpdateCheck>("update_check"),
	vaultStatus: () => __TAURI_INVOKE<VaultStatus>("vault_status"),
	/**  VAULT-01/02: creates the vault and returns the recovery code (shown exactly once). */
	vaultCreate: (password: string) => __TAURI_INVOKE<string>("vault_create", { password }),
	/**  VAULT-03 / SEC-06: wrong passwords are throttled with increasing delays (persisted). */
	vaultUnlock: (password: string) => __TAURI_INVOKE<null>("vault_unlock", { password }),
	/**  SEC-07 (P1): Windows Hello. */
	vaultUnlockBiometric: () => __TAURI_INVOKE<null>("vault_unlock_biometric"),
	vaultLock: () => __TAURI_INVOKE<void>("vault_lock"),
	vaultVerifyPassword: (password: string) => __TAURI_INVOKE<boolean>("vault_verify_password", { password }),
	/**
	 *  VAULT-05: re-wraps only the vault key (no item is re-encrypted); with sync, the server copy is
	 *  updated atomically and other devices' sessions are revoked.
	 */
	vaultChangePassword: (current: string, next: string) => __TAURI_INVOKE<null>("vault_change_password", { current, next }),
	/**  VAULT-06: resets the master password with the recovery code. Works offline when sync is off. */
	vaultRecover: (recoveryCode: string, newPassword: string) => __TAURI_INVOKE<null>("vault_recover", { recoveryCode, newPassword }),
	/**  Flow B (§6.6): first launch on a new device — download the vault from the cloud. */
	vaultRestoreFromCloud: (config: SyncConfigInput, password: string) => __TAURI_INVOKE<null>("vault_restore_from_cloud", { config, password }),
	/**  VAULT-07: single-file encrypted backup in the same envelope format. */
	vaultExportBackup: (path: string) => __TAURI_INVOKE<null>("vault_export_backup", { path }),
	/**  Issues a new recovery code (the old one stops working everywhere once synced). */
	vaultRotateRecovery: (password: string) => __TAURI_INVOKE<string>("vault_rotate_recovery", { password }),
	/**  SEC-07 (P1): enrol Windows Hello. Requires the master password as a fresh confirmation. */
	biometricEnable: (password: string) => __TAURI_INVOKE<null>("biometric_enable", { password }),
	biometricDisable: () => __TAURI_INVOKE<null>("biometric_disable"),
	hostsList: () => __TAURI_INVOKE<HostView[]>("hosts_list"),
	hostGet: (id: string) => __TAURI_INVOKE<HostView>("host_get", { id }),
	hostSave: (input: HostInput) => __TAURI_INVOKE<HostView>("host_save", { input }),
	hostDelete: (id: string) => __TAURI_INVOKE<null>("host_delete", { id }),
	hostDuplicate: (id: string) => __TAURI_INVOKE<HostView>("host_duplicate", { id }),
	hostSetFavorite: (id: string, favorite: boolean) => __TAURI_INVOKE<null>("host_set_favorite", { id, favorite }),
	/**
	 *  SEC-08: copies a saved host password to the clipboard from Rust (it never reaches the WebView)
	 *  and clears it after 30 s if the clipboard still holds it.
	 */
	hostCopyPassword: (id: string) => __TAURI_INVOKE<null>("host_copy_password", { id }),
	groupsList: () => __TAURI_INVOKE<GroupView[]>("groups_list"),
	groupSave: (input: GroupInput) => __TAURI_INVOKE<GroupView>("group_save", { input }),
	groupDelete: (id: string) => __TAURI_INVOKE<null>("group_delete", { id }),
	tagsList: () => __TAURI_INVOKE<TagCount[]>("tags_list"),
	/**  HOST-10: TCP connect only (no authentication), 3 s timeout, probed concurrently. */
	hostsProbe: (ids: string[]) => __TAURI_INVOKE<ProbeResult[]>("hosts_probe", { ids }),
	sshConfigPreview: () => __TAURI_INVOKE<SshConfigCandidate[]>("ssh_config_preview"),
	/**  SSH-11: creates hosts (and imports unencrypted identity files as keys) for the chosen aliases. */
	sshConfigImport: (aliases: string[]) => __TAURI_INVOKE<ImportResult>("ssh_config_import", { aliases }),
	keysList: () => __TAURI_INVOKE<KeyView[]>("keys_list"),
	/**  KEY-01 / WIN-09: OpenSSH, PEM and PuTTY .ppk, from a file or pasted text, with clear errors. */
	keyImport: (input: KeyImportInput) => __TAURI_INVOKE<KeyView>("key_import", { input }),
	/**  KEY-02: Ed25519 by default, RSA 4096 optional. */
	keyGenerate: (input: KeyGenerateInput) => __TAURI_INVOKE<KeyView>("key_generate", { input }),
	keyRename: (id: string, name: string) => __TAURI_INVOKE<KeyView>("key_rename", { id, name }),
	/**  KEY-05: the UI lists the hosts using the key before calling this; they fall back to "ask". */
	keyDelete: (id: string) => __TAURI_INVOKE<null>("key_delete", { id }),
	keyPublic: (id: string) => __TAURI_INVOKE<string>("key_public", { id }),
	/**
	 *  KEY-06: appends the public key to `~/.ssh/authorized_keys` on a host (like `ssh-copy-id`).
	 *  The key travels on stdin, so nothing from it is interpreted by the remote shell.
	 */
	keyDeploy: (keyId: string, hostId: string) => __TAURI_INVOKE<null>("key_deploy", { keyId, hostId }),
	sshConnect: (hostId: string, options: ConnectOptions, channel: Channel<TermFrame>) => __TAURI_INVOKE<string>("ssh_connect", { hostId, options, channel }),
	sshWrite: (sessionId: string, data: string) => __TAURI_INVOKE<null>("ssh_write", { sessionId, data }),
	sshResize: (sessionId: string, cols: number, rows: number) => __TAURI_INVOKE<null>("ssh_resize", { sessionId, cols, rows }),
	sshDisconnect: (sessionId: string) => __TAURI_INVOKE<null>("ssh_disconnect", { sessionId }),
	/**  "Test connection" in the host editor: connect, authenticate, verify the host key, disconnect. */
	sshTest: (input: HostInput) => __TAURI_INVOKE<TestResult>("ssh_test", { input }),
	hostkeyRespond: (requestId: string, accept: boolean) => __TAURI_INVOKE<void>("hostkey_respond", { requestId, accept }),
	authPromptRespond: (requestId: string, answers: string[] | null) => __TAURI_INVOKE<void>("auth_prompt_respond", { requestId, answers }),
	forwardsList: (hostId: string) => __TAURI_INVOKE<ForwardView[]>("forwards_list", { hostId }),
	forwardSave: (input: ForwardInput) => __TAURI_INVOKE<ForwardView>("forward_save", { input }),
	forwardDelete: (id: string) => __TAURI_INVOKE<null>("forward_delete", { id }),
	forwardStart: (sessionId: string, forwardId: string) => __TAURI_INVOKE<number>("forward_start", { sessionId, forwardId }),
	forwardStop: (sessionId: string, forwardId: string) => __TAURI_INVOKE<null>("forward_stop", { sessionId, forwardId }),
	/**  Forwards currently running on a session: `(forward_id, local_port)`. */
	forwardsActive: (sessionId: string) => __TAURI_INVOKE<([string, number])[]>("forwards_active", { sessionId }),
	sftpHome: (sessionId: string) => __TAURI_INVOKE<string>("sftp_home", { sessionId }),
	sftpList: (sessionId: string, path: string) => __TAURI_INVOKE<FileEntry[]>("sftp_list", { sessionId, path }),
	/**  SFTP-02 download. `local_path` comes from the native save dialog. */
	sftpDownload: (sessionId: string, remotePath: string, localPath: string) => __TAURI_INVOKE<string>("sftp_download", { sessionId, remotePath, localPath }),
	/**  SFTP-02 upload into `remote_dir` (file picker or drag & drop). */
	sftpUpload: (sessionId: string, localPath: string, remoteDir: string) => __TAURI_INVOKE<string>("sftp_upload", { sessionId, localPath, remoteDir }),
	sftpRename: (sessionId: string, from: string, to: string) => __TAURI_INVOKE<null>("sftp_rename", { sessionId, from, to }),
	sftpRemove: (sessionId: string, path: string, isDir: boolean) => __TAURI_INVOKE<null>("sftp_remove", { sessionId, path, isDir }),
	sftpMkdir: (sessionId: string, path: string) => __TAURI_INVOKE<null>("sftp_mkdir", { sessionId, path }),
	transferCancel: (transferId: string) => __TAURI_INVOKE<void>("transfer_cancel", { transferId }),
	syncStatus: () => __TAURI_INVOKE<SyncStatus>("sync_status"),
	/**  Wizard "Test connection": Worker `/v1/health`, or (D1 mode) token check + database list. */
	syncTest: (config: SyncConfigInput) => __TAURI_INVOKE<SyncTestResult>("sync_test", { config }),
	/**  Flow A (§6.6): initialise the remote with this vault, sign in and push everything. */
	syncConfigure: (config: SyncConfigInput, password: string) => __TAURI_INVOKE<null>("sync_configure", { config, password }),
	syncNow: () => __TAURI_INVOKE<null>("sync_now"),
	/**  Re-authenticate after "认证失效" (session expired or revoked). */
	syncLogin: (password: string) => __TAURI_INVOKE<null>("sync_login", { password }),
	/**  The sync status page opened: reads the Worker's `/v1/health` (§6.7, Upgrades). */
	syncCheckWorker: () => __TAURI_INVOKE<void>("sync_check_worker"),
	/**  Hides "Worker update available" until the app bundles a newer Worker version. */
	syncDismissWorkerUpdate: () => __TAURI_INVOKE<null>("sync_dismiss_worker_update"),
	syncSetAuto: (enabled: boolean) => __TAURI_INVOKE<void>("sync_set_auto", { enabled }),
	/**  Stops syncing on this device. Local data and the remote copy are both kept. */
	syncDisconnect: () => __TAURI_INVOKE<null>("sync_disconnect"),
	syncDevices: () => __TAURI_INVOKE<DeviceView[]>("sync_devices"),
	syncRevokeDevice: (deviceId: string) => __TAURI_INVOKE<null>("sync_revoke_device", { deviceId }),
	/**  §6.4: conflicts are resolved automatically; this lists the unreviewed ones (P1). */
	syncConflicts: () => __TAURI_INVOKE<ConflictView[]>("sync_conflicts"),
	syncConflictResolve: (id: number, action: ConflictAction) => __TAURI_INVOKE<null>("sync_conflict_resolve", { id, action }),
	/**
	 *  Step 1 (DEPLOY-02): checks the API token. The token crosses to Rust here once; every later
	 *  call names the deployment by the returned handle (DEPLOY-07).
	 */
	deployStart: (apiToken: string, accountId: string | null) => __TAURI_INVOKE<DeployStart>("deploy_start", { apiToken, accountId }),
	/**  Step 2: what the deployment will do, before anything is written. */
	deployInspect: (handle: string, target: DeployTarget) => __TAURI_INVOKE<DeployPlan>("deploy_inspect", { handle, target }),
	/**
	 *  Steps 2 to 8 (DEPLOY-03), reporting each step on `progress`. Run it again after a failure to
	 *  continue the deployment (DEPLOY-05).
	 */
	deployRun: (handle: string, target: DeployTarget, progress: Channel<DeployProgress>) => __TAURI_INVOKE<DeployOutcome>("deploy_run", { handle, target, progress }),
	/**  "Check again" while step 8 waits for the Worker. */
	deployCheck: (handle: string) => __TAURI_INVOKE<boolean>("deploy_check", { handle }),
	/**  "Remove what Hatoba created": only what this deployment created (DEPLOY-05). */
	deployCleanup: (handle: string) => __TAURI_INVOKE<null>("deploy_cleanup", { handle }),
	/**  Ends the deployment and forgets its tokens (the user cancelled or left the wizard). */
	deployCancel: (handle: string) => __TAURI_INVOKE<void>("deploy_cancel", { handle }),
	/**
	 *  The master password step after a deployment: Flow A step 3 (§6.6) with the Worker URL and the
	 *  setup token from the deployment, then deletes the `SETUP_TOKEN` secret (DEPLOY-06) and ends
	 *  the deployment.
	 */
	deploySetup: (handle: string, password: string) => __TAURI_INVOKE<null>("deploy_setup", { handle, password }),
	/**
	 *  What "Update Worker" starts from (DEPLOY-08): the account ID and Worker name recorded when the
	 *  app deployed the Worker, or else the name in its workers.dev URL.
	 */
	deployUpgradeDefaults: () => __TAURI_INVOKE<UpgradeDefaults>("deploy_upgrade_defaults"),
	/**  Step 2 of an upgrade: what it will do, before anything is written. */
	deployUpgradeInspect: (handle: string, target: UpgradeTarget) => __TAURI_INVOKE<UpgradePlan>("deploy_upgrade_inspect", { handle, target }),
	/**
	 *  "Update Worker" (DEPLOY-08): the deployment steps as an upgrade, reporting each step on
	 *  `progress`. Run it again after a failure to continue the upgrade.
	 */
	deployUpgrade: (handle: string, target: UpgradeTarget, progress: Channel<DeployProgress>) => __TAURI_INVOKE<DeployOutcome>("deploy_upgrade", { handle, target, progress }),
	settingsGet: () => __TAURI_INVOKE<SettingsView>("settings_get"),
	settingsSave: (settings: SettingsView) => __TAURI_INVOKE<null>("settings_save", { settings }),
	/**  Readable while locked: the unlock screen needs the language. */
	prefsGet: () => __TAURI_INVOKE<LocalPrefs>("prefs_get"),
	prefsSave: (prefs: LocalPrefs) => __TAURI_INVOKE<null>("prefs_save", { prefs }),
	/**  The sidebar's star prompt (spec §9). The first read records when this device started waiting. */
	starPromptGet: () => __TAURI_INVOKE<StarPrompt>("star_prompt_get"),
	/**  The user starred, opened the bug report form, or closed the prompt: it never shows again. */
	starPromptDone: () => __TAURI_INVOKE<null>("star_prompt_done"),
};

/** Events */
export const events = {
	sshAuthPrompt: makeEvent<AuthPrompt>("ssh://auth-prompt"),
	sshForward: makeEvent<ForwardStatusEvent>("ssh://forward"),
	sshHostkeyPrompt: makeEvent<HostKeyPrompt>("ssh://hostkey-prompt"),
	sshState: makeEvent<SessionStateEvent>("ssh://state"),
	syncStatus: makeEvent<SyncStatus>("sync://status"),
	transferProgress: makeEvent<TransferProgressEvent>("transfer://progress"),
	vaultLocked: makeEvent<VaultLockedEvent>("vault://locked"),
};

/* Types */
export type AppError = {
	code: ErrorCode,
	detail: string,
	retry_at: number | null,
	field: string | null,
	ssh_kind: SshErrorKind | null,
	key_kind: KeyParseErrorKind | null,
	permission: CloudflarePermission | null,
	cf_code: number | null,
};

export type AppInfo = {
	version: string,
	platform: Platform,
	mica: boolean,
};

export type Appearance = "system" | "light" | "dark";

export type AuthKind = "password" | "key" | "agent" | "ask";

export type AuthPrompt = {
	request_id: string,
	session_id: string | null,
	name: string,
	instructions: string,
	prompts: AuthPromptField[],
};

export type AuthPromptField = {
	prompt: string,
	echo: boolean,
};

export type CloudflareAccount = {
	id: string,
	name: string,
};

export type CloudflarePermission = "workers_scripts" | "d1";

export type ConflictAction = "keep" | "restore";

export type ConflictField = {
	field: string,
	local: string | null,
	remote: string | null,
};

export type ConflictResolution = "local_won" | "remote_won" | "kept_both" | "modified_won";

export type ConflictView = {
	id: number,
	item_id: string,
	item_type: ItemType,
	item_name: string,
	resolution: ConflictResolution,
	local_updated_at: number | null,
	remote_updated_at: number | null,
	local_deleted: boolean,
	remote_deleted: boolean,
	fields: ConflictField[],
	created_at: number,
};

export type ConnectOptions = {
	cols: number,
	rows: number,
	/**  `ask` auth (SSH-03): used once, never stored. */
	password: string | null,
	passphrase: string | null,
};

export type CursorChoice = "block" | "bar" | "underline";

export type D1Database = {
	id: string,
	name: string,
	region: string | null,
};

export type Density = "regular" | "compact";

export type DeployDatabaseAction = "create" | 
/**  An existing database with nothing but Hatoba's migrations. */
"use" | 
/**  The database already bound to the Hatoba Worker. */
"bound";

export type DeployOutcome = {
	url: string,
	/**  `false`: the Worker has not answered yet (step 8 is waiting); `deploy_check` asks again. */
	ready: boolean,
};

/**  What step 2 found, shown before anything is written. */
export type DeployPlan = {
	/**  The account's workers.dev subdomain; `None` means the user has to choose one. */
	subdomain: string | null,
	worker: DeployWorkerAction,
	database: DeployDatabaseAction | null,
	database_name: string | null,
};

/**  Sent on the `deploy_run` channel as each step starts and ends. */
export type DeployProgress = {
	step: DeployStep,
	status: DeployStepStatus,
};

/**  Step 1 passed. Later calls name the deployment by `handle`; the API token stays in Rust. */
export type DeployStart = {
	handle: string,
	/**  The token belongs to the account given with it rather than to a user. */
	account_owned: boolean,
	/**  The accounts a user token reaches; empty when the user has to enter the account ID. */
	accounts: CloudflareAccount[],
	/**  The default Worker and database names. */
	worker_name: string,
	database_name: string,
};

export type DeployStep = "verify" | "inspect" | "create_database" | "migrate" | "upload" | "setup_token" | "route" | "wait";

export type DeployStepStatus = "running" | "done" | "skipped";

export type DeployTarget = {
	account_id: string,
	worker_name: string,
	database_name: string,
	/**  The workers.dev subdomain to create when the account has none. */
	subdomain: string | null,
};

export type DeployWorkerAction = "create" | "update" | 
/**  A Hatoba Worker whose database holds a vault: the deployment stops. */
"has_vault" | 
/**  A Worker the app does not recognize: the deployment stops. */
"foreign";

export type DeviceView = {
	device_id: string,
	name: string,
	platform: string,
	created_at: number,
	last_seen: number,
	current: boolean,
};

export type ErrorCode = "locked" | "not_initialized" | "already_initialized" | "wrong_password" | "wrong_recovery_code" | "throttled" | "not_found" | "invalid_input" | "key_parse" | "ssh" | "sftp" | "sync" | "sync_auth" | "sync_offline" | "remote_initialized" | "remote_not_initialized" | 
/**  In-app deployment (§6.7): Cloudflare rejected the API token. */
"cloudflare_token" | 
/**  The API token lacks the permission in `permission`. */
"cloudflare_permission" | 
/**  Any other Cloudflare API failure; `cf_code` has Cloudflare's code when it sent one. */
"cloudflare" | "subdomain_required" | "subdomain_unavailable" | "worker_name_taken" | 
/**  An upgrade found no Hatoba Worker with a vault under the name. */
"worker_not_found" | 
/**  An upgrade found a Worker newer than the one this build deploys. */
"worker_newer" | 
/**  This build does not embed the Worker, so it cannot deploy it. */
"no_worker_bundle" | "cancelled" | "io" | "internal";

export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	is_symlink: boolean,
	size: number,
	modified: number | null,
	permissions: string,
};

export type ForwardInput = {
	id: string | null,
	host_id: string,
	bind_address: string,
	bind_port: number,
	dest_host: string,
	dest_port: number,
	auto_start: boolean,
};

export type ForwardState = "running" | "stopped" | "failed";

/**  A forward's state on one live session. */
export type ForwardStatusEvent = {
	session_id: string,
	forward_id: string,
	state: ForwardState,
	/**  The actually bound local port (differs from `bind_port` when it was 0). */
	local_port: number | null,
	error: string | null,
};

/**  A saved local (`-L`) forward. Remote and dynamic forwards are P2. */
export type ForwardView = {
	id: string,
	host_id: string,
	bind_address: string,
	bind_port: number,
	dest_host: string,
	dest_port: number,
	auto_start: boolean,
};

export type GenerateAlgorithm = "ed25519" | "rsa";

export type GroupInput = {
	id: string | null,
	name: string,
	parent_id: string | null,
	sort: number,
};

export type GroupView = {
	id: string,
	name: string,
	parent_id: string | null,
	sort: number,
};

export type HostInput = {
	id: string | null,
	name: string,
	address: string,
	port: number,
	username: string,
	auth_kind: AuthKind,
	/**  `None` keeps the saved password (HOST-08). */
	password: string | null,
	key_id: string | null,
	group_id: string | null,
	tags: string[],
	favorite: boolean,
	jump_host_id: string | null,
	note: string,
};

export type HostKeyPrompt = {
	request_id: string,
	session_id: string | null,
	host: string,
	port: number,
	key_type: string,
	fingerprint: string,
	kind: HostKeyPromptKind,
	known_fingerprint: string | null,
	known_key_type: string | null,
};

export type HostKeyPromptKind = "new" | "changed";

export type HostView = {
	id: string,
	name: string,
	address: string,
	port: number,
	username: string,
	auth_kind: AuthKind,
	has_password: boolean,
	key_id: string | null,
	group_id: string | null,
	tags: string[],
	favorite: boolean,
	jump_host_id: string | null,
	note: string,
	updated_at: number,
	last_connected_at: number | null,
};

export type ImportResult = {
	hosts_created: number,
	keys_imported: number,
	warnings: string[],
};

export type ItemType = "host" | "group" | "key" | "known_host" | "forward" | "snippet" | "settings";

export type KeyAlgorithm = "ed25519" | "ecdsa" | "rsa";

export type KeyGenerateInput = {
	name: string,
	algorithm: GenerateAlgorithm,
	comment: string,
	passphrase: string | null,
};

export type KeyImportInput = {
	name: string,
	private_key: string | null,
	path: string | null,
	passphrase: string | null,
};

export type KeyParseErrorKind = "unsupported_format" | "passphrase_required" | "wrong_passphrase" | "unsupported_algorithm" | "invalid";

export type KeyView = {
	id: string,
	name: string,
	algorithm: KeyAlgorithm,
	bits: number,
	public_key: string,
	fingerprint: string,
	comment: string,
	has_passphrase: boolean,
	created_at: number,
	updated_at: number,
	used_by: string[],
};

export type Language = "system" | "zh-CN" | "en" | "ja";

/**  Device-local UI preferences (readable while locked; never synced). */
export type LocalPrefs = {
	language: Language,
	appearance: Appearance,
	density: Density,
	host_probe: boolean,
	/**
	 *  Check GitHub for a newer release once after unlock. Off by default: no request leaves
	 *  the device unless the user asks for it (spec §11, no telemetry).
	 */
	auto_update_check: boolean,
};

export type LockReason = "manual" | "idle" | "sleep";

export type Platform = "windows" | "macos" | "linux";

export type ProbeResult = {
	id: string,
	online: boolean,
	latency_ms: number | null,
};

export type RightClick = "copy_paste" | "menu";

export type SessionState = "connecting" | "connected" | "disconnected" | "failed";

export type SessionStateEvent = {
	session_id: string,
	host_id: string,
	state: SessionState,
	latency_ms: number | null,
	error: AppError | null,
	exit_status: number | null,
};

export type SettingsView = {
	terminal: TerminalSettings,
	auto_lock_minutes: number,
	lock_disconnects_sessions: boolean,
};

export type SshConfigCandidate = {
	alias: string,
	address: string,
	port: number,
	username: string,
	identity_file: string | null,
	proxy_jump: string | null,
	exists: boolean,
};

export type SshErrorKind = "dns" | "refused" | "timeout" | "unreachable" | "auth_failed" | "host_key_rejected" | "key_parse" | "disconnected" | "protocol" | "io" | "channel" | "sftp" | "cancelled" | "other";

/**  Device-local state of the sidebar's GitHub star prompt (spec §9; never synced). */
export type StarPrompt = {
	/**  When this device first read the state, Unix ms. The prompt waits a day from then. */
	first_seen_at: number,
	/**  The user starred the repository, opened the bug report form, or closed the prompt. */
	done: boolean,
};

export type SyncConfigInput = { kind: "worker"; url: string; setup_token: string | null } | { kind: "d1"; account_id: string; database_id: string; api_token: string };

export type SyncCounts = {
	hosts: number,
	keys: number,
	groups: number,
};

export type SyncKind = "none" | "worker" | "d1";

export type SyncState = "off" | "idle" | "syncing" | "offline" | "auth_failed" | "error" | 
/**  The Worker's version stops sync until it or the app is updated; `worker_update` says which. */
"paused";

export type SyncStatus = {
	kind: SyncKind,
	endpoint: string | null,
	database: string | null,
	state: SyncState,
	last_synced_at: number | null,
	pending: number,
	conflicts: number,
	auto_sync: boolean,
	message: string | null,
	counts: SyncCounts | null,
	/**
	 *  Worker mode: how the Worker's `/v1/health` compares with this build (§6.7, Upgrades).
	 *  `None` when there is nothing to show, including a dismissed "update available".
	 */
	worker_update: WorkerUpdate | null,
};

export type SyncTestResult = {
	ok: boolean,
	initialized: boolean,
	version: string | null,
	latency_ms: number | null,
	databases: D1Database[] | null,
	error: AppError | null,
};

export type TagCount = {
	name: string,
	count: number,
};

/**
 *  One terminal frame on the per-session channel: tag byte + payload. Sent through Tauri's raw
 *  binary IPC path (an `ArrayBuffer` in the WebView), never as a JSON number array (§10.3).
 */
export type TermFrame = number[];

export type TerminalSettings = {
	font_family: string,
	font_size: number,
	theme: ThemeChoice,
	cursor_style: CursorChoice,
	scrollback: number,
	right_click: RightClick,
	confirm_multiline_paste: boolean,
};

export type TestResult = {
	ok: boolean,
	latency_ms: number | null,
	host_key_verified: boolean,
	error: AppError | null,
};

export type ThemeChoice = "system" | "light" | "dark";

export type TransferDirection = "upload" | "download";

export type TransferProgressEvent = {
	transfer_id: string,
	session_id: string,
	direction: TransferDirection,
	name: string,
	bytes: number,
	total: number,
	bytes_per_sec: number,
	state: TransferState,
	error: string | null,
};

export type TransferState = "running" | "done" | "failed" | "cancelled";

/**  What the update check found on GitHub Releases (spec §11). */
export type UpdateCheck = {
	current_version: string,
	/**  The newest stable release, or `None` when none has been published yet. */
	latest_version: string | null,
	/**  The release page to download the installer from. */
	release_url: string | null,
	update_available: boolean,
};

/**  What the "Update Worker" form starts from (§6.7, Upgrades). */
export type UpgradeDefaults = {
	/**  The Worker URL in the sync settings. */
	url: string,
	/**  The account ID, when the app deployed the Worker. */
	account_id: string | null,
	/**
	 *  The Worker name: recorded when the app deployed it, or the first label of a workers.dev
	 *  URL. `None` for a custom domain, where the user enters it.
	 */
	worker_name: string | null,
	/**
	 *  The app deployed the Worker. Otherwise it may have come from the Deploy to Cloudflare
	 *  button, whose next push from the user's repository replaces the upgrade.
	 */
	deployed_by_app: boolean,
};

/**  What step 2 of an upgrade found, shown before anything is written. */
export type UpgradePlan = {
	worker: UpgradeWorkerAction,
	/**  The database bound to the Worker. */
	database_name: string | null,
	/**  Migrations step 4 applies. */
	migrations: number,
	/**  Step 7 runs: the Worker URL is its workers.dev URL. */
	route: boolean,
	/**  The version the Worker URL reports, when it answers. */
	version: string | null,
	/**  The version the upgrade deploys. */
	bundled: string,
};

export type UpgradeTarget = {
	account_id: string,
	worker_name: string,
};

export type UpgradeWorkerAction = "upgrade" | 
/**  No Worker has the name: the upgrade stops. */
"missing" | 
/**  A Worker the app does not recognize: the upgrade stops. */
"foreign" | 
/**  A Hatoba Worker without a vault: the upgrade stops. */
"no_vault" | 
/**  The Worker is newer than the bundled version: the upgrade stops. */
"newer";

export type VaultLockedEvent = {
	reason: LockReason,
};

export type VaultState = "uninitialized" | "locked" | "unlocked";

export type VaultStatus = {
	state: VaultState,
	failed_attempts: number,
	retry_at: number | null,
	sync_kind: SyncKind,
	biometric_available: boolean,
	biometric_enabled: boolean,
};

export type WorkerUpdate = {
	kind: WorkerUpdateKind,
	/**  The version the Worker reports. */
	version: string,
	/**  The version "Update Worker" deploys; `None` in builds without the Worker bundle. */
	bundled: string | null,
};

export type WorkerUpdateKind = 
/**  Older than the bundled version: sync continues, and the update can be dismissed. */
"available" | 
/**  Older than the minimum version, or a lower `api`: sync is paused. */
"required" | 
/**  A newer `api` than this app speaks: sync is paused until Hatoba is updated. */
"app_required";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

