/**
 * Compile-time check that the hand-written IPC contract (`types.ts`) matches the Rust DTOs exported
 * by tauri-specta (`bindings.ts`, regenerate with `cargo test -p hatoba-desktop export_bindings`).
 * Responses/events must be assignable Rust → UI; inputs UI → Rust. `tsc` fails on any drift.
 */
import type * as Rust from "./bindings";
import type * as Ui from "./types";

type Assignable<A, B> = [A] extends [B] ? true : false;
type Check<T extends true> = T;

/** Rust → UI: command results and events. */
export type ResponsesMatch = [
  Check<Assignable<Rust.AppError, Ui.AppError>>,
  Check<Assignable<Rust.AppInfo, Ui.AppInfo>>,
  Check<Assignable<Rust.UpdateCheck, Ui.UpdateCheck>>,
  Check<Assignable<Rust.VaultStatus, Ui.VaultStatus>>,
  Check<Assignable<Rust.HostView, Ui.HostView>>,
  Check<Assignable<Rust.GroupView, Ui.GroupView>>,
  Check<Assignable<Rust.TagCount, Ui.TagCount>>,
  Check<Assignable<Rust.SshConfigCandidate, Ui.SshConfigCandidate>>,
  Check<Assignable<Rust.ImportResult, Ui.ImportResult>>,
  Check<Assignable<Rust.ProbeResult, Ui.ProbeResult>>,
  Check<Assignable<Rust.KeyView, Ui.KeyView>>,
  Check<Assignable<Rust.SessionStateEvent, Ui.SessionStateEvent>>,
  Check<Assignable<Rust.HostKeyPrompt, Ui.HostKeyPrompt>>,
  Check<Assignable<Rust.AuthPrompt, Ui.AuthPrompt>>,
  Check<Assignable<Rust.TestResult, Ui.TestResult>>,
  Check<Assignable<Rust.FileEntry, Ui.FileEntry>>,
  Check<Assignable<Rust.TransferProgressEvent, Ui.TransferProgressEvent>>,
  Check<Assignable<Rust.SyncStatus, Ui.SyncStatus>>,
  Check<Assignable<Rust.SyncTestResult, Ui.SyncTestResult>>,
  Check<Assignable<Rust.DeviceView, Ui.DeviceView>>,
  Check<Assignable<Rust.ConflictView, Ui.ConflictView>>,
  Check<Assignable<Rust.SettingsView, Ui.SettingsView>>,
  Check<Assignable<Rust.LocalPrefs, Ui.LocalPrefs>>,
  Check<Assignable<Rust.StarPrompt, Ui.StarPrompt>>,
  Check<Assignable<Rust.VaultLockedEvent, Ui.VaultLockedEvent>>,
  Check<Assignable<Rust.ForwardView, Ui.ForwardView>>,
  Check<Assignable<Rust.ForwardStatusEvent, Ui.ForwardStatusEvent>>,
  Check<Assignable<Rust.DeployStart, Ui.DeployStart>>,
  Check<Assignable<Rust.DeployPlan, Ui.DeployPlan>>,
  Check<Assignable<Rust.DeployProgress, Ui.DeployProgress>>,
  Check<Assignable<Rust.DeployOutcome, Ui.DeployOutcome>>,
  Check<Assignable<Rust.UpgradeDefaults, Ui.UpgradeDefaults>>,
  Check<Assignable<Rust.UpgradePlan, Ui.UpgradePlan>>,
  Check<Assignable<Rust.AiProviderView, Ui.AiProviderView>>,
  Check<Assignable<Rust.AiModel, Ui.AiModel>>,
  Check<Assignable<Rust.AiTestResult, Ui.AiTestResult>>,
  Check<Assignable<Rust.SearchProviderView, Ui.SearchProviderView>>,
  Check<Assignable<Rust.AiSettingsView, Ui.AiSettingsView>>,
  Check<Assignable<Rust.AiConversationView, Ui.AiConversationView>>,
  Check<Assignable<Rust.AiConversationDetail, Ui.AiConversationDetail>>,
  Check<Assignable<Rust.AiEntryView, Ui.AiEntryView>>,
  Check<Assignable<Rust.AiSendStarted, Ui.AiSendStarted>>,
  Check<Assignable<Rust.AiTurnEvent, Ui.AiTurnEvent>>,
  Check<Assignable<Rust.AiSearchHit, Ui.AiSearchHit>>,
  Check<Assignable<Rust.SkillView, Ui.SkillView>>,
  Check<Assignable<Rust.SkillDetail, Ui.SkillDetail>>,
  Check<Assignable<Rust.SkillFileView, Ui.SkillFileView>>,
  Check<Assignable<Rust.SkillIssue, Ui.SkillIssue>>,
  Check<Assignable<Rust.SkillImportPreview, Ui.SkillImportPreview>>,
  Check<Assignable<Rust.BuiltinSkillView, Ui.BuiltinSkillView>>,
  Check<Assignable<Rust.McpTransportView, Ui.McpTransportView>>,
  Check<Assignable<Rust.McpServerView, Ui.McpServerView>>,
  Check<Assignable<Rust.McpServerState, Ui.McpServerState>>,
  Check<Assignable<Rust.McpToolAnnotations, Ui.McpToolAnnotations>>,
  Check<Assignable<Rust.McpToolView, Ui.McpToolView>>,
  Check<Assignable<Rust.McpServerStatus, Ui.McpServerStatus>>,
  Check<Assignable<Rust.McpServerStatus, Ui.EventMap["ai://mcp-status"]>>,
  Check<Assignable<Rust.McpToolInfo, Ui.McpToolInfo>>,
  Check<Assignable<Rust.McpImportPreview, Ui.McpImportPreview>>,
];

/** UI → Rust: command arguments. */
export type InputsMatch = [
  Check<Assignable<Ui.HostInput, Rust.HostInput>>,
  Check<Assignable<Ui.GroupInput, Rust.GroupInput>>,
  Check<Assignable<Ui.KeyImportInput, Rust.KeyImportInput>>,
  Check<Assignable<Ui.KeyGenerateInput, Rust.KeyGenerateInput>>,
  Check<Assignable<Ui.ConnectOptions, Rust.ConnectOptions>>,
  Check<Assignable<Ui.SyncConfigInput, Rust.SyncConfigInput>>,
  Check<Assignable<Ui.SettingsView, Rust.SettingsView>>,
  Check<Assignable<Ui.LocalPrefs, Rust.LocalPrefs>>,
  Check<Assignable<Ui.ForwardInput, Rust.ForwardInput>>,
  Check<Assignable<Ui.DeployTarget, Rust.DeployTarget>>,
  Check<Assignable<Ui.UpgradeTarget, Rust.UpgradeTarget>>,
  Check<Assignable<Ui.AiProviderInput, Rust.AiProviderInput>>,
  Check<Assignable<Ui.AiModel, Rust.AiModel>>,
  Check<Assignable<Ui.SearchProviderInput, Rust.SearchProviderInput>>,
  Check<Assignable<Ui.AiSettingsView, Rust.AiSettingsView>>,
  Check<Assignable<Ui.AiSendInput, Rust.AiSendInput>>,
  Check<Assignable<Ui.AiTurnContext, Rust.AiTurnContext>>,
  Check<Assignable<Ui.AiToolResultInput, Rust.AiToolResultInput>>,
  Check<Assignable<Ui.SkillInput, Rust.SkillInput>>,
  Check<Assignable<Ui.SkillFileView, Rust.SkillFileView>>,
  Check<Assignable<Ui.McpServerInput, Rust.McpServerInput>>,
  Check<Assignable<Ui.McpTransportInput, Rust.McpTransportInput>>,
  Check<Assignable<Ui.McpSecretInput, Rust.McpSecretInput>>,
];
